### ISSUE TITLE
5) Encourage/enable lots of little contributions

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/collaborative-lesson-development#35]
This is the longest rule, since it discusses/compares/evaluates mechanics.

**Comment by ianmilligan1** [comment]
## 5) Encourage and enable lots of little contributions.

It takes a village to ensure a long-lasting lesson. Steady improvement and adaptation of a lesson will make it live longer. Ensuring this, however, is not straightforward.

Making the process explicit is key. New contributors require an on-ramp to understand the process of tweaking and adapting lessons; licensing, code of conduct, governance, and contribution procedure need to all be explicit rather than implicit. All of this serves to lower the social barriers to contribution.

Tools can help, especially if they support pre-merge review. Yet some of these tools come with a considerable up-front learning curve. GitHub with pull requests may be ideal, but allowing people to edit a Google Doc, or to facilitate Wiki-based editing, can help get conversations started. In a pinch, work with contributors to find a comfort zone –-- don't let a collaboration flounder on technological choice. But make sure not to overwhelm either; threaded discussion (or GitHub issues) will help increase the signal-to-noise ratio.

Ultimately, community dynamics are more important than platform. We follow the 90/9/1 rule (90% of people watch, 9% discuss, 1% do). This requires a gentle on-ramp for new contributors, that we make it easy for people to submit errata and suggestions, and that editors may need to do triage to ensure that voices are heard. Finally, with so many voices and contributions come caution. Working in the open can be great, but can also unintentionally suppress voices. At _Programming Historian_, a popular digital humanities technical site, an ombudsperson is available for private chats and facilitation. Many voices are great, as long as they can all be considered.

**Comment by gdevenyi** [comment]
Does it make sense to use the term "on-ramp"? It might be a bit too ameri-anglo-centric of an analogy (or do we define it?) If I didn't know what an on-ramp was, this paragraph could be quite confusing.

**Comment by ianmilligan1** [comment]
Sounds good to me @gdevenyi!

**Comment by gvwilson** [comment]
Good work - please close this issue when the PR is updated and merged.
