### ISSUE TITLE
7) Publish each lesson periodically

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/collaborative-lesson-development#37]
Credit is important for sustainability.

**Comment by gdevenyi** [comment]
Similar to publishing software, lessons should have releases of fixed content so that learners or instructors who may wish to use the material have a stable version to refer to for the duration of their use. These releases should be periodic so that improvements and adjustments are made available for new learners and instructors just starting their use. Periodic releases are also essential for enabling recognition of the contribution of authors and maintainers.
The traditional academic system has limited ways of recognizing contributions. Until systems have been expanded to improve this, it is important to publish your lessons using a mechanism that provides recognition to the contributors. Currently an effective way to do this is to publish lessons with a DOI supplied by (list possibilities). Contributors can be listed as Authors and the maintainers of the lesson as Editors to provide differentiated recognition of their contributions.

**Comment by twitwi** [comment]
I integrated your paragraphs and added a couple on how to release.

For now it is there https://github.com/gvwilson/collaborative-lesson-development/blob/wip-rule-7/notes.md
