### ISSUE TITLE
8) Feedback

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/collaborative-lesson-development#38]
Mention classroom practice (minute cards etc.), but talk more about how that turns into issues to be fixed and items for discussion.

**Comment by DamienIrving** [comment]
### Rule: Collect and act on feedback at several scales.

The purpose of feedback is to guide lesson development so that authors aren't designing and arguing in a vacuum. What people immersed in the lessons think needs fixing can often differ from what learners think needs fixing.

Micro-scale feedback can be gathered by an instructor while teaching a particular lesson. Learners might provide feedback on things like typographical errors, clarity/ease of quiz questions or the order in which topics are presented, which the instructor can enter into a work-tracking system (e.g. GitHub issues) at the end of class. As well as encouraging direct verbal feedback, it's a good idea to provide learners with a means to provide feedback anonymously during class (e.g. small pieces of paper like sticky notes).  

Pre- and post-class surveys can be used to discover larger macro-scale issues. If possible, it's a good idea to conduct the post-class survey 30-60 days after the fact. This allows people time to reflect, meaning they are more likely to give accurate feedback on what they learned rather than how entertained they were.

**Comment by gdevenyi** [comment]
Pre- and post- class surveys also are essential in focusing in on the audience for a given lesson. It can be difficult for lesson developers to sometimes understand the frame of a given learner so especially post-class surveys can reveal hidden assumed knowledge that can be expanded on or acknowledged.

**Comment by gvwilson** [comment]
:+1: to @gdevenyi's addition - @DamienIrving can you please add to the PR?
